import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import UserProvider from "./context/UserProvider";
import EncounterProvider from "./context/EncounterProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DnD Encounter Creator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <EncounterProvider>
            <header className="flex bg-black aboslute">
              <Image src="/dnd_logo.png" alt="Logo" width={100} height={50} />
              <Link href="/" className="text-white p-3 hover:bg-gray-800">
                Home
              </Link>
              <Link
                href="/encounters"
                className="text-white p-3 hover:bg-gray-800"
              >
                Encounters
              </Link>
              <Link href="/about" className="text-white p-3 hover:bg-gray-800">
                About
              </Link>
            </header>
            {children}
          </EncounterProvider>
        </UserProvider>
      </body>
    </html>
  );
}
